const mongoose = require("mongoose");
const dotenv = require("dotenv");
dotenv.config({ path: ".env" });
const Vehicle = require("../models/Vehicle");

const vehicles = [
  {
    VIN: "JT2BG22K0V1234567",
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    type: "Sedan",
    price: 14500,
    cost: 12000,
    purchaseDate: new Date("2024-04-14"),
    insuranceProvider: "AXA",
    insuranceExpiry: new Date("2025-04-14"),
    maintenanceCost: 200,
    fuelCost: 1100,
    transmission: "Automatic",
    cylinders: "4",
    fuelType: "Petrol",
    condition: "Used",
    color: "#ffffff",
    status: "Active",
    stock: 4,
    images: [],
  },
  {
    VIN: "2HGFB2F50DH765432",
    make: "Honda",
    model: "Civic",
    year: 2021,
    type: "Sedan",
    price: 13800,
    cost: 11500,
    purchaseDate: new Date("2024-02-20"),
    insuranceProvider: "Libano-Suisse",
    insuranceExpiry: new Date("2025-02-20"),
    maintenanceCost: 240,
    fuelCost: 1050,
    transmission: "Automatic",
    cylinders: "4",
    fuelType: "Petrol",
    condition: "Used",
    color: "#000000",
    status: "Active",
    stock: 3,
    images: [],
  },
  {
    VIN: "JTDKN3DU4F1987654",
    make: "Toyota",
    model: "Camry",
    year: 2023,
    type: "Sedan",
    price: 24500,
    cost: 20500,
    purchaseDate: new Date("2024-07-01"),
    insuranceProvider: "Bankers",
    insuranceExpiry: new Date("2025-07-01"),
    maintenanceCost: 160,
    fuelCost: 980,
    transmission: "Automatic",
    cylinders: "6",
    fuelType: "Hybrid",
    condition: "New",
    color: "#34495e",
    status: "Active",
    stock: 2,
    images: [],
  },
  {
    VIN: "5XYKT3A16EG765890",
    make: "Kia",
    model: "Sportage",
    year: 2023,
    type: "SUV",
    price: 26000,
    cost: 22000,
    purchaseDate: new Date("2024-06-18"),
    insuranceProvider: "Allianz",
    insuranceExpiry: new Date("2025-06-18"),
    maintenanceCost: 180,
    fuelCost: 1500,
    transmission: "Automatic",
    cylinders: "6",
    fuelType: "Petrol",
    condition: "New",
    color: "#8e44ad",
    status: "Active",
    stock: 5,
    images: [],
  },
  {
    VIN: "KM8J3CA46GU123987",
    make: "Hyundai",
    model: "Tucson",
    year: 2022,
    type: "SUV",
    price: 21900,
    cost: 18200,
    purchaseDate: new Date("2024-05-12"),
    insuranceProvider: "MetLife",
    insuranceExpiry: new Date("2025-05-12"),
    maintenanceCost: 190,
    fuelCost: 1350,
    transmission: "Automatic",
    cylinders: "6",
    fuelType: "Petrol",
    condition: "Used",
    color: "#2c3e50",
    status: "Active",
    stock: 3,
    images: [],
  },
  {
    VIN: "1FTFW1EF9HFA98765",
    make: "Ford",
    model: "F-150",
    year: 2020,
    type: "Truck",
    price: 29500,
    cost: 24000,
    purchaseDate: new Date("2024-03-07"),
    insuranceProvider: "AXA",
    insuranceExpiry: new Date("2025-03-07"),
    maintenanceCost: 350,
    fuelCost: 2000,
    transmission: "Automatic",
    cylinders: "8",
    fuelType: "Petrol",
    condition: "Used",
    color: "#b71540",
    status: "Active",
    stock: 1,
    images: [],
  },
  {
    VIN: "WAULC68E04A123654",
    make: "Audi",
    model: "A6",
    year: 2019,
    type: "Sedan",
    price: 18000,
    cost: 15000,
    purchaseDate: new Date("2024-01-30"),
    insuranceProvider: "Libano-Suisse",
    insuranceExpiry: new Date("2025-01-30"),
    maintenanceCost: 420,
    fuelCost: 1600,
    transmission: "Automatic",
    cylinders: "6",
    fuelType: "Petrol",
    condition: "Used",
    color: "#7f8c8d",
    status: "Active",
    stock: 2,
    images: [],
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ Connected");

    await Vehicle.deleteMany();
    console.log("🗑️ Previous Data Cleared");

    await Vehicle.insertMany(vehicles);
    console.log("🚗 7 Vehicles Seeded Successfully!");

    process.exit();
  } catch (err) {
    console.error("❌ Error:", err);
    process.exit(1);
  }
};

seed();
